Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/jammy64"  # Ubuntu 22.04 LTS
  
  config.vm.provider "virtualbox" do |vb|
    vb.memory = "2048"  # Allocate 2GB RAM
    vb.cpus = 2         # Use 2 CPU cores
  end

  # Ensure the synced folder works correctly on Windows
  #config.vm.synced_folder ".", "/vagrant", disabled: true  # Disable default sync
  config.vm.synced_folder "C:\\Users\\edwin\\Desktop\\DevMachine\\CVersion\\server", "/home/ubuntu/.", type: "virtualbox"
  config.vm.synced_folder "C:\\Users\\edwin\\Desktop\\DevMachine\\CVersion\\buildfiles\\", "/root/.vs/TestProj/out/build/linux-debug/.", type: "virtualbox"
  config.vm.synced_folder "C:\\Users\\edwin\\Desktop\\DevMachine\\GoVersion\\client", "/home/ubuntu/.", type: "virtualbox"
  config.vm.network "public_network", bridge: "enp0s3"
  config.vm.network "forwarded_port", guest: 4222, host: 4222

  # Optional: Provisioning inside the VM
  config.vm.provision "shell", inline: <<-SHELL
    echo "Installing Build tools."
    sudo apt-get install software-properties-common
    sudo apt-add-repository ppa:lttng/stable-2.13
    sudo add-apt-repository ppa:george-edison55/cmake-3.x
    sudo apt-get update
    sudo apt install -y cmake net-tools build-essential cmake ninja-build unzip curl zip git lttng-tools
    sudo apt-get upgrade -y
    git clone https://github.com/microsoft/vcpkg.git
    cd vcpkg
    ./bootstrap-vcpkg.sh
    cd ..
    echo "cd /home/ubuntu" >> /home/vagrant/.bashrc
    source /home/vagrant/.bashrc
    ssh-keygen -m pem -t ecdsa -f /home/vagrant/vstudio -N ""
    sudo cat /home/vagrant/vstudio.pub >> /root/.ssh/authorized_keys
    echo "Generated Key Pub:\n"
    cat /home/vagrant/vstudio.pub
    echo "\nGenerated Key Priv:\n"
    cat /home/vagrant/vstudio
  SHELL
end

