Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/jammy64"  # Ubuntu 22.04 LTS
  
  config.vm.provider "virtualbox" do |vb|
    vb.memory = "2048"  # Allocate 2GB RAM
    vb.cpus = 2         # Use 2 CPU cores
  end

  # Ensure the synced folder works correctly on Windows
  #config.vm.synced_folder ".", "/vagrant", disabled: true  # Disable default sync
  config.vm.synced_folder "C:\\Users\\edwin\\Desktop\\DevMachine\\client", "/home/ubuntu/.", type: "virtualbox"
  config.vm.network "public_network", bridge: "enp0s3"
  #config.vm.network "forwarded_port", guest: 4242, host: 4242

  # Optional: Provisioning inside the VM
  config.vm.provision "shell", inline: <<-SHELL
    sudo apt install net-tools
    echo "Installing golang."
    wget https://go.dev/dl/go1.23.5.linux-amd64.tar.gz
    sudo rm -rf /usr/local/go  # Remove any existing Go installation
    sudo tar -C /usr/local -xzf go1.23.5.linux-amd64.tar.gz
    echo 'export PATH=$PATH:/usr/local/go/bin' >> /home/vagrant/.bashrc
    echo 'export GOPATH=$HOME/go' >> /home/vagrant/.bashrc
    echo 'export PATH=$PATH:$GOPATH/bin' >> /home/vagrant/.bashrc
    source /home/vagrant/.bashrc
  SHELL
end
